### ISSUE TITLE
Command line arguments for sensor and transfo tree names in blini imports

### ISSUE THREAD

**Issue by mbredif** [LI3DS/micmac_li3ds#2]
For now, KeyIm2TimeCam is used to provide a name for various object during blini import. That is a sensible default as this is the only available string (together with the blini filename), but it may cause trouble if we require name unicity and is usually not very informative (eg `Loc-Assoc-Im2Block`).

I propose to add 2 command line arguments to allow the optional specifications of the names of the `sensor` and of the `transfotree`.

As multiple calibrations of the same group are likely to have multiple filenames with the same KeyIm2TimeCam tag, I propose the following :
- default `sensor name` : `KeyIm2TimeCam`
- default `transfotree name` : `blinis_file_basename`

Sensor `name` and `id` arguments could then be made exclusive : 
- no sensor name, no sensor id -> sensor creation with default name
- sensor name only -> sensor lookup by name, sensor creation with the given name if not found
- sensor id only -> sensor lookup by id, failure if not found

**Comment by elemoine** [comment]
That sounds good to me @mbredif. I'll go ahead and implement that.

**Comment by elemoine** [comment]
By the way, sensors have no name right now :) But they have `model`, `short_name`, `brand` and `serial_number`. I can use `short_name` but it would make more sense to have `name` to me.

**Comment by mbredif** [comment]
agreed, see [#2](/LI3DS/pg_li3ds/issues/2)

**Comment by elemoine** [comment]
See https://github.com/LI3DS/micmac_li3ds/commit/bcb4434291b3e5adc259cc2b8b90ad8b904d4abe. Although `short_name` rather than `name` is used for now.

**Comment by elemoine** [comment]
Closing this issue then. The sensor name issue is tracked with other tickets.

**Comment by mbredif** [comment]
Great, thanks !
