### ISSUE TITLE
Repo name to rename

### ISSUE THREAD

**Issue by elemoine** [LI3DS/micmac_li3ds#27]
As it does more than importing data from micmac. Suggestion: cli-li3ds.

**Comment by mbredif** [comment]
agreed

**Comment by ldgeo** [comment]
ok go for cli-li3ds

**Comment by elemoine** [comment]
Ok, I'll work on that. I'll remane the repo `cli-li3ds`, and I'll change name of the command line from `mm2li` to `li3ds`.
