### ISSUE TITLE
Dynamic transfo type ids

### ISSUE THREAD

**Issue by mbredif** [LI3DS/micmac_li3ds#3]
Transfo types are currently [hard coded](https://github.com/LI3DS/micmac_li3ds/blob/61fce3b9a0d4f1b335449550f4d3722e042244ac/micmac_li3ds/import_blinis.py#L192)

This could be centralised into a python object so that the transfo_type id is more explicit (by looking up transfo_type id by name), and so that this object could be populated dynamically using http://api.li3ds.io/transfos/types/.

**Comment by elemoine** [comment]
I am not sure I understand. Do you mind elaborating a bit?

**Comment by mbredif** [comment]
Instead of hard coding `'transfo_type': 1,`, you could do `'transfo_type': transfo_type['affine'],` where `transfo_type` is a dictionnary populated using /transfos/types/ endpoint of the li3ds api.

**Comment by elemoine** [comment]
Ok.

**Comment by elemoine** [comment]
@mbredif look at http://api.li3ds.io/transfos/types/. Transfo types have no names. This means that I have no key for the `transfo_type` dict mapping "transfo type names" (e.g. "affine") to "transfo type id". Do you agree that a "name" is required there as well?

**Comment by mbredif** [comment]
I think "func_name" should be renamed as "name". You can use func_name in the meantime.

**Comment by elemoine** [comment]
Oh ok, I thought the func signature did not include the actual func name. But I understand that it does… Thanks.

**Comment by elemoine** [comment]
Done with https://github.com/LI3DS/micmac_li3ds/commit/09ac27dc25fc2ccde47a65f1ac12ae9df958d705
